version: 2.1

executors:
  ci:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:12.16.2
  cd:
    docker:
      - image: circleci/golang:1.9.6
    working_directory: ~/workspace

commands:
  persist-build:
    steps:
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - ./build
  attach-build:
    steps:
      - attach_workspace:
          at: ~/workspace

  yarn-install:
    steps:
      - restore_cache:
          key: npm-cache-{{ checksum "package.json" }}
      - run:
          name: install node_modules
          command: yarn
      - save_cache:
          key: npm-cache-{{ checksum "package.json" }}
          paths:
              - node_modules
  yarn-build:
    steps:
      - run: yarn build
  deploy-to-s3:
    steps:
      - run:
          name: Deploy to S3
          command: s3deploy -source=~/workspace/build -region=ap-northeast-1 -key=$PROD_AWS_ACCESS_KEY_ID -secret=$PROD_AWS_SECRET_ACCESS_KEY -distribution-id=$AWS_CLOUDFRONT_DISTRIBUTION_ID -bucket=$BUCKET_NAME

jobs:
  build:
    executor:
      name: ci
    steps:
      - checkout
      - yarn-install
      - yarn-build
      - persist-build
  deploy:
    executor:
      name: cd
    steps:
      - attach-build
      - deploy-to-s3

workflows:
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          # filters:
          #   branches:
          #     only:
          #       - master
